name: Auto Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json

    - name: Deploy to Google Cloud Storage
      run: |
        gsutil cp -r ./ gs://staging.test-shopping-428314.appspot.com/

    - name: Deploy to Google Cloud App Engine
      run: |
        gcloud app deploy app.yaml --quiet
