name: Auto Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Deploy to Google Cloud Storage
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS="key.json"
        gsutil -m rsync -r ./ gs://test-shopping-428314.appspot.com/
